import type { GalleryItem } from "@/types";

export const gallery = {
  eyebrow: { bn: "মুহূর্তগুলো", en: "Memorable Moments" } as const,
  title: { bn: "গ্যালারি", en: "Gallery" } as const,
  subtitle: {
    bn: "আমার শিক্ষাজীবন, অর্জন, সামাজিক কার্যক্রম ও উদ্যোগের কিছু মুহূর্ত",
    en: "Some moments from my education, achievements, social work, and initiatives",
  } as const,
  categories: [
    { icon: "🏆", label: { bn: "অর্জন", en: "Achievements" } },
    { icon: "🩸", label: { bn: "রক্তদান", en: "Blood Donation" } },
    { icon: "📚", label: { bn: "শিক্ষা", en: "Education" } },
    { icon: "🤝", label: { bn: "সমাজসেবা", en: "Social Work" } },
  ] as const,
  items: [
    {
      src: "/images/ssc-gpa5-2025.jpg",
      alt: "Rahat Ahmed SSC 2025 GPA 5.00 A+ achievement",
      title: { bn: "SSC 2025 — GPA 5.00 (A+)", en: "SSC 2025 — GPA 5.00 (A+)" },
      meta: { bn: "১০ জুলাই, ২০২৫", en: "July 10, 2025" },
      badge: "🏆",
    },
    {
      src: "/images/ssc-songbordhona-2025.jpg",
      alt: "Rahat Ahmed at Meritorious Student Honor Ceremony",
      title: { bn: "কৃতী শিক্ষার্থী সংবর্ধনা", en: "Meritorious Student Honor" },
      meta: { bn: "সাতগাঁও জীবদাড়া উচ্চ বিদ্যালয়", en: "Satgaon Jibdara High School" },
      badge: "🎗️",
    },
    {
      src: "/images/ssc-crest-shantichakra.jpg",
      alt: "Recognition crest from Shantichakra Blood Society",
      title: { bn: "শান্তিচক্র সম্মাননা ক্রেস্ট", en: "Shantichakra Honor Crest" },
      meta: { bn: "২০২৫", en: "2025" },
      badge: "🩸",
      missing: true,
    },
    {
      src: "/images/shantichakra-blood-society.jpg",
      alt: "Shantichakra Blood Society Sunamganj activities",
      title: { bn: "শান্তিচক্র ব্লাড সোসাইটি", en: "Shantichakra Blood Society" },
      meta: { bn: "সহ-প্রতিষ্ঠাতা ও সাধারণ সম্পাদক", en: "Co-Founder & General Secretary" },
      badge: "🩸",
      missing: true,
    },
    {
      src: "/images/46-science-fair-2025.jpg",
      alt: "46th National Science Fair 2025 achievement",
      title: { bn: "৪৬তম বিজ্ঞান মেলা", en: "46th Science Fair" },
      meta: { bn: "২০২৫ — ১ম স্থান (কুইজ)", en: "2025 — 1st (Quiz)" },
      badge: "🥇",
      missing: true,
    },
    {
      src: "/images/srijonshil-medha-2024.jpg",
      alt: "Creative Talent Search Competition 2024 - 1st Place in Science",
      title: { bn: "সৃজনশীল মেধা অন্বেষণ", en: "Creative Talent Search" },
      meta: { bn: "২০২৪ — বিজ্ঞানে ১ম স্থান", en: "2024 — 1st in Science" },
      badge: "🧠",
      missing: true,
    },
    {
      src: "/images/44-science-fair-2024.jpg",
      alt: "44th National Science Exhibition 2024 - 1st Place",
      title: { bn: "৪৪তম বিজ্ঞান প্রদর্শনী", en: "44th Science Exhibition" },
      meta: { bn: "২ মে, ২০২৪ — ১ম স্থান", en: "May 2, 2024 — 1st Place" },
      badge: "🏆",
      missing: true,
    },
    {
      src: "/images/45-science-fair-2023.jpg",
      alt: "45th National Science Fair 2023 achievements",
      title: { bn: "৪৫তম বিজ্ঞান মেলা", en: "45th Science Fair" },
      meta: { bn: "৩১ আগস্ট, ২০২৩", en: "August 31, 2023" },
      badge: "🥇",
    },
    {
      src: "/images/42-science-fair-2020.jpg",
      alt: "42nd National Science Fair 2020 - First win",
      title: { bn: "৪২তম বিজ্ঞান মেলা", en: "42nd Science Fair" },
      meta: { bn: "২৬ নভেম্বর, ২০২০ — প্রথম জয়", en: "Nov 26, 2020 — First Win" },
      badge: "🥇",
      missing: true,
    },
    {
      src: "/images/fs-coaching-center.jpg",
      alt: "FS Coaching Center at Jibdara Bazar",
      title: { bn: "FS কোচিং সেন্টার", en: "FS Coaching Center" },
      meta: { bn: "প্রতিষ্ঠিত ৩১ ডিসেম্বর, ২০২৪", en: "Founded Dec 31, 2024" },
      badge: "🏫",
      missing: true,
    },
    {
      src: "/images/helping-hand-org.jpg",
      alt: "Helping Hand Organization activities",
      title: { bn: "হেল্পিং হ্যান্ড অর্গানাইজেশন", en: "Helping Hand Organization" },
      meta: { bn: "প্রতিষ্ঠিত ২০২৩", en: "Founded 2023" },
      badge: "🤝",
    },
  ] as GalleryItem[],
  info: {
    text: {
      bn: "আরও ছবি ও মুহূর্ত পেতে আমার সোশ্যাল মিডিয়া অনুসরণ করুন",
      en: "Follow my social media for more photos and moments",
    },
    cta: { bn: "সংযুক্ত হোন", en: "Connect with me" },
  } as const,
};
